package com.hao.demo.qiu.dao;

import com.hao.demo.qiu.model.DemoUser;
import com.hao.demo.qiu.model.DemoUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface DemoUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user
     *
     * @mbggenerated
     */
    int countByExample(DemoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user
     *
     * @mbggenerated
     */
    int deleteByExample(DemoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user
     *
     * @mbggenerated
     */
    @Delete({
        "delete from demo_user",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user
     *
     * @mbggenerated
     */
    @Insert({
        "insert into demo_user (id, name, ",
        "age, moile, address, ",
        "sex, height, weight, ",
        "back)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{age,jdbcType=INTEGER}, #{moile,jdbcType=VARCHAR}, #{address,jdbcType=VARCHAR}, ",
        "#{sex,jdbcType=INTEGER}, #{height,jdbcType=DOUBLE}, #{weight,jdbcType=DOUBLE}, ",
        "#{back,jdbcType=VARCHAR})"
    })
    int insert(DemoUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user
     *
     * @mbggenerated
     */
    int insertSelective(DemoUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user
     *
     * @mbggenerated
     */
    List<DemoUser> selectByExample(DemoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, name, age, moile, address, sex, height, weight, back",
        "from demo_user",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    DemoUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DemoUser record, @Param("example") DemoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DemoUser record, @Param("example") DemoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DemoUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user
     *
     * @mbggenerated
     */
    @Update({
        "update demo_user",
        "set name = #{name,jdbcType=VARCHAR},",
          "age = #{age,jdbcType=INTEGER},",
          "moile = #{moile,jdbcType=VARCHAR},",
          "address = #{address,jdbcType=VARCHAR},",
          "sex = #{sex,jdbcType=INTEGER},",
          "height = #{height,jdbcType=DOUBLE},",
          "weight = #{weight,jdbcType=DOUBLE},",
          "back = #{back,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(DemoUser record);
}